### ISSUE TITLE
hpack-convert won't build with LTS11.4

### ISSUE THREAD

**Issue by sebeaumont** [yamadapc/hpack-convert#18]
```
$ stack install hpack-convert
Using latest snapshot resolver: lts-11.4
```
    /private/var/folders/30/9xrf_jtx7618zqb1pyd1wyh40000gp/T/stack40077/hpack-convert-1.0.1/src/Hpack/Util.hs:106:21: error:
        • Couldn't match type ‘[[FilePath]]’ with ‘([[FilePath]], b0)’
          Expected type: IO ([[FilePath]], b0)
            Actual type: IO [[FilePath]]
        • In the second argument of ‘(<$>)’, namely
            ‘globDir compiledPatterns dir’
          In the first argument of ‘(>>=)’, namely
            ‘(fst <$> globDir compiledPatterns dir)’
          In a stmt of a 'do' block:
            files <- (fst <$> globDir compiledPatterns dir)
                       >>= mapM removeDirectories
        |
    106 |   files <- (fst <$> globDir compiledPatterns dir) >>= mapM removeDirectories
        |                     ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by tebello-thejane** [comment]
It would appear that the type signature for `globDir` changed in `Glob-0.9.0`.

Old: https://hackage.haskell.org/package/Glob-0.8.0/docs/System-FilePath-Glob.html#v:globDir
```Haskell
globDir :: [Pattern] -> FilePath -> IO ([[FilePath]], [FilePath]) 
```
New: https://hackage.haskell.org/package/Glob-0.9.0/docs/System-FilePath-Glob.html#v:globDir
```Haskell
globDir :: [Pattern] -> FilePath -> IO [[FilePath]] 
```

This appears to be a simple job for `-XCPP`, assuming that nothing else is broken.

**Comment by tebello-thejane** [comment]
Here's a supposed fix: https://github.com/yamadapc/hpack-convert/pull/16

**Comment by ifduyue** [comment]
Any updates on this?

**Comment by andrewufrank** [comment]
I observed the same error - with ghc 8.4.4 
please fix!

**Comment by CedricLeong** [comment]
I'm getting the same error on Windows 10

**Comment by peterstorm** [comment]
Any update for this? Doesn't work on newest resolver either, as far as my tries go :(

**Comment by pigam** [comment]
Interested as well for #16 integration.

**Comment by wbadart** [comment]
Looks like we've still got this issue on LTS-15.5.

**Comment by chansey97** [comment]
At the moment the hpack-convert won't build with the latest GHC (such as 9.8.1, ghc-9.4.8), and the [official repository](https://github.com/yamadapc/hpack-convert/releases) doesn't provide a windows binary release. This prevents you from using hpack-convert on windows. 

You might built it via older snapshot by stack, but this require downgrading the stack version, which is annoying.

For ease of use, a windows binary is provided [here](https://github.com/chansey97/hpack-convert/releases/tag/v1.0.3).

It built on windows (lts-15.5) successfully and it works well, using @kindaro 's fork: https://github.com/kindaro/hpack-convert/commit/fa98909f18992713fba82d2033e04fdedb58592a

Related links: https://github.com/yamadapc/hpack-convert/issues/18 https://github.com/yamadapc/hpack-convert/pull/16

**Comment by sebeaumont** [comment]
Please close this if everyone's happy -- (I can't recall what I was doing in 2018)  and I don't use stack anymore these days anyhow.
